version: '3.9'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html/wordpress
    restart: always
    networks:
      - myIncNet

  mariadb:
    container_name: mariadb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - myIncNet
    restart: always
    env_file:
      - .env
    build:
      context: ./requirements/mariadb
      args:
        MARIADB_DATABASE: ${MARIADB_DATABASE}
        MARIADB_USER: ${MARIADB_USER}
        MARIADB_PASSWORD: ${MARIADB_PASSWORD}
        MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}

  wordpress:
    build: ./requirements/wordpress
    env_file:
      - .env
    container_name: wordpress
    networks:
      - myIncNet
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html/wordpress
    restart: always

  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp
    depends_on:
      - wordpress
      # - redis
    volumes:
      - wordpress_data:/home/aandom/ftp/files
    env_file:
      - .env
    ports:
      - "21:21"
      - "20:20"
      - "4000-4005:4000-4005"
    networks:
      - myIncNet
    restart: always

  redis:
    container_name: redis
    restart: always
    build: ./requirements/bonus/redis
    networks:
      - myIncNet
    ports:
      - "6379:6379"
    env_file:
      - .env
    # depends_on:
    #   - wordpress
    volumes:
      - redis_data:/var/lib/redis

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    networks:
      - myIncNet
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: always

  samba:
    container_name: samba
    build:
      context: ./requirements/bonus/samba
      args:
        SMB_USER: ${SMB_USER}
        SMB_PASSWORD: ${SMB_PASSWORD}
    volumes:
      - wordpress_data:/data
    networks:
      - myIncNet
    ports:
      - "139:139"
      - "445:445"
    env_file:
      - .env
    restart: always

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wp
  db_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/db
  redis_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/rd

networks:
  myIncNet:
    driver: bridge